#!/usr/bin/env python3
"""build-standalone.py — generate web/index.standalone.html from the web/ sources.

Mode 2 (standalone) breaks when opened from Android's Files app, because that hands
the browser a content:// URI: a content-provider URI points at ONE file's bytes and
has no sibling directory, so every relative <link href="css/…"> / <script src="js/…">
fails to load and you get an unstyled, dead page.

This tool inlines all of those assets into a single self-contained HTML file so there
are ZERO relative fetches — it then renders correctly however it is opened (content://,
file://, http://). It is a *build step*, not a second copy: web/ stays the only
hand-edited source of truth; this file is regenerated and is git-ignored.

    python3 build-standalone.py            # writes web/index.standalone.html

What gets inlined:
  - css/styles.css                      -> <style>
  - vendor/highlight-light|dark.css     -> live <style id="hljs-theme"> + two inert
                                           text blocks the theme toggle reads from
  - every <script src="…">              -> <script>…</script>
  - vendor/mermaid.min.js (2.6 MB)      -> inert <script id="mermaid-src"> that app.js
                                           lazy-loads via a Blob URL (see app.js)

The matching runtime branches live in web/js/app.js (feature-detected on element
presence), so the SAME source serves both server and standalone modes.
"""

from __future__ import annotations

import os
import re
import sys

APP_DIR = os.path.dirname(os.path.abspath(__file__))
WEB_DIR = os.path.join(APP_DIR, "web")
SRC = os.path.join(WEB_DIR, "index.html")
OUT = os.path.join(WEB_DIR, "index.standalone.html")

# The two stylesheet <link>s in index.html, matched verbatim (fail loudly if they
# move — that means index.html changed and this build must be revisited).
HLJS_LINK = '<link rel="stylesheet" href="vendor/highlight-light.css" id="hljs-theme">'
STYLES_LINK = '<link rel="stylesheet" href="css/styles.css">'
VENDOR_COMMENT = "<!-- vendored libs (offline, no CDN) -->"

SCRIPT_RE = re.compile(r'<script src="([^"]+)"></script>')


def read(rel: str) -> str:
    path = os.path.join(WEB_DIR, rel)
    with open(path, "r", encoding="utf-8") as fh:
        return fh.read()


def guard_script(text: str) -> str:
    """Neutralise any literal </script in inlined JS/text so it can't close the tag.

    `<\\/script` is byte-identical to `</script` once the text is run as JS (the
    backslash only appears inside string/regex/comment contexts in real bundles),
    and harmless inside an inert text/plain block we read via textContent."""
    return re.sub(r"</(script)", r"<\\/\1", text, flags=re.IGNORECASE)


def inline_style(css: str, attrs: str = "") -> str:
    if "</style" in css.lower():
        sys.exit("refusing to inline CSS containing </style")
    space = (" " + attrs) if attrs else ""
    return f"<style{space}>\n{css}\n</style>"


def main() -> int:
    if not os.path.isfile(SRC):
        sys.exit(f"not found: {SRC}")
    html = read("index.html")

    # 1) highlight theme: one live <style> (seeded light) + both themes as inert text.
    light = read("vendor/highlight-light.css")
    dark = read("vendor/highlight-dark.css")
    if HLJS_LINK not in html:
        sys.exit("could not find the hljs-theme <link> — did index.html change?")
    hljs_block = "\n".join([
        inline_style(light, 'id="hljs-theme"'),
        f'<script type="text/plain" id="hljs-light-src">\n{guard_script(light)}\n</script>',
        f'<script type="text/plain" id="hljs-dark-src">\n{guard_script(dark)}\n</script>',
    ])
    html = html.replace(HLJS_LINK, hljs_block, 1)

    # 2) main stylesheet.
    if STYLES_LINK not in html:
        sys.exit("could not find the styles.css <link> — did index.html change?")
    html = html.replace(STYLES_LINK, inline_style(read("css/styles.css")), 1)

    # 3) mermaid (lazy): inert text block app.js turns into a Blob URL on first diagram.
    mermaid_block = (
        f'<script type="text/plain" id="mermaid-src">'
        f'{guard_script(read("vendor/mermaid.min.js"))}</script>\n  {VENDOR_COMMENT}'
    )
    if VENDOR_COMMENT in html:
        html = html.replace(VENDOR_COMMENT, mermaid_block, 1)
    else:
        sys.exit("could not find the vendor-libs comment anchor — did index.html change?")

    # 4) every <script src="…"> -> inline <script>…</script>.
    inlined = []

    def repl(m: "re.Match[str]") -> str:
        rel = m.group(1)
        inlined.append(rel)
        return f"<script>\n{guard_script(read(rel))}\n</script>"

    html = SCRIPT_RE.sub(repl, html)
    if not inlined:
        sys.exit("no <script src> tags matched — did index.html change?")

    banner = "<!-- GENERATED by build-standalone.py from web/ — do not edit; edit the sources. -->\n"
    html = html.replace("<!DOCTYPE html>", "<!DOCTYPE html>\n" + banner, 1)

    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(html)

    size = os.path.getsize(OUT)
    print(f"wrote {os.path.relpath(OUT, APP_DIR)}  ({size / 1024:.0f} KiB)")
    print(f"  inlined {len(inlined)} scripts + styles + mermaid; 0 relative fetches remain")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
